{% set python_min = '3.11' %}
{% set name = "nionswift-instrumentation" %}
{% set version = "23.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 44bded6e17e7db6d3402b755bd874b180fa1aa782ab6dc92bb5642c91763b24a

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - niondata >=15.7,<16.0
    - nionswift >=16.12,<17.0
    - nionui >=8.0,<9.0
    - nionutils >=4.12,<5.0
    - numpy >=2.0,<3.0
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - nion.instrumentation
    - nion.instrumentation.test
    - nionswift_plugin.nion_instrumentation_ui

about:
  home: https://nionswift-instrumentation.readthedocs.io
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: A Nion Swift library for STEM instrumentation (Camera, Scan, Video, Microscope).
  doc_url: https://nionswift-instrumentation.readthedocs.io
  dev_url: https://github.com/nion-software/nionswift-instrumentation-kit

extra:
  recipe-maintainers:
    - cmeyer
    - nion-gwyn
