{% set name = "nionswift-instrumentation" %}
{% set version = "22.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cad9dd6b8552bce7d93b352fdaddc97614df08119c9c7b9d10a60ec2a98bc309

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - niondata >=15.6.0,<16.0.0
    - nionswift >=16.9.0,<17.0.0
    - nionui >=7.0.0,<8.0.0
    - nionutils >=0.4.8,<5.0.0
    - python >=3.9
    - numpy >=1.25,<2.0

test:
  imports:
    - nion.instrumentation
    - nion.instrumentation.test
    - nionswift_plugin.nion_instrumentation_ui

about:
  home: https://nionswift-instrumentation.readthedocs.io
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: A Nion Swift library for STEM instrumentation (Camera, Scan, Video, Microscope).
  doc_url: https://nionswift-instrumentation.readthedocs.io
  dev_url: https://github.com/nion-software/nionswift-instrumentation-kit

extra:
  recipe-maintainers:
    - cmeyer
    - nion-gwyn
