{% set name = "nionswift-instrumentation" %}
{% set version = "0.19.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6e74ca0042f7c5146dcc80521ee36611c508149df29e45a482d59e1ba1af4ebc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - nionswift >=0.15.0
    - python >=3.7

test:
  imports:
    - nion.instrumentation
    - nion.instrumentation.test
    - nionswift_plugin.nion_instrumentation_ui

about:
  home: https://nionswift-instrumentation.readthedocs.io
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: A Nion Swift library for STEM instrumentation (Camera, Scan, Video, Microscope).
  doc_url: https://nionswift-instrumentation.readthedocs.io
  dev_url: https://github.com/nion-software/nionswift-instrumentation-kit

extra:
  recipe-maintainers:
    - cmeyer
    - nion-gwyn
