{% set name = "nionswift-instrumentation" %}
{% set version = "0.20.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3718694271e0045cca7821fa48175e2690c95efd3dfef6898699c54eb3d775d2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - nionui >=0.5.0,<0.6.0
    - nionswift >=0.15.5,<0.16.0
    - python >=3.7

test:
  imports:
    - nion.instrumentation
    - nion.instrumentation.test
    - nionswift_plugin.nion_instrumentation_ui

about:
  home: https://nionswift-instrumentation.readthedocs.io
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: A Nion Swift library for STEM instrumentation (Camera, Scan, Video, Microscope).
  doc_url: https://nionswift-instrumentation.readthedocs.io
  dev_url: https://github.com/nion-software/nionswift-instrumentation-kit

extra:
  recipe-maintainers:
    - cmeyer
    - nion-gwyn
