{% set python_min = "3.11" %}
{% set name = "nionswift-instrumentation" %}
{% set version = "23.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 11b8ea4de4a24e53000a8fc5fb81125f37991621d1bc1e3ba68f4c7c1d998670

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - niondata >=15.8,<16.0
    - nionswift >=16.15,<17.0
    - nionui >=10.0,<11.0
    - nionutils >=4.14,<5.0
    - numpy >=2.0,<3.0
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - nion.instrumentation
    - nion.instrumentation.test
    - nionswift_plugin.nion_instrumentation_ui

about:
  home: https://nionswift-instrumentation.readthedocs.io
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: A Nion Swift library for STEM instrumentation (Camera, Scan, Video, Microscope).
  doc_url: https://nionswift-instrumentation.readthedocs.io
  dev_url: https://github.com/nion-software/nionswift-instrumentation-kit

extra:
  recipe-maintainers:
    - cmeyer
    - nion-gwyn
